In [103]:
import os
import shutil
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_datasets as tfds

print("Version: ", tf.__version__)
print("Eager mode: ", tf.executing_eagerly())
print("Hub version: ", hub.__version__)
print("GPU is", "available" if tf.config.list_physical_devices("GPU") 
      else "NOT AVAILABLE")

Version:  2.6.0-dev20210510
Eager mode:  True
Hub version:  0.8.0
GPU is NOT AVAILABLE


In [2]:
# Downloading the IMDB dataset
# Split the training set into 60% and 40% to end up with 15,000 examples
# for training, 10,000 examples for validation and 25,000 examples for testing.
url = "https://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz"

dataset = tf.keras.utils.get_file("aclImdb_v1", url,
                                    untar=True, cache_dir='.',
                                    cache_subdir='')

dataset_dir = os.path.join(os.path.dirname(dataset), 'aclImdb')

train_dir = os.path.join(dataset_dir, 'train')

remove_dir = os.path.join(train_dir, 'unsup')
shutil.rmtree(remove_dir)

In [85]:
# Preparing train, test and validation datasets
batch_size = 32
seed = 42

train_data = tf.keras.preprocessing.text_dataset_from_directory(
    'aclImdb/train', 
    batch_size=batch_size, 
    validation_split=0.2, 
    subset='training', 
    seed=seed)

validation_data = tf.keras.preprocessing.text_dataset_from_directory(
    'aclImdb/train', 
    batch_size=batch_size, 
    validation_split=0.2, 
    subset='validation', 
    seed=seed)

test_data = tf.keras.preprocessing.text_dataset_from_directory(
    'aclImdb/test', 
    batch_size=batch_size)

AUTOTUNE = tf.data.AUTOTUNE

train_data = train_data.cache().prefetch(buffer_size=AUTOTUNE)
validation_data = validation_data.cache().prefetch(buffer_size=AUTOTUNE)
test_data = test_data.cache().prefetch(buffer_size=AUTOTUNE)

Found 25000 files belonging to 2 classes.
Using 20000 files for training.
Found 25000 files belonging to 2 classes.
Using 5000 files for validation.
Found 25000 files belonging to 2 classes.


In [86]:
# Exploring the data
train_examples_batch, train_labels_batch = next(iter(train_data.batch(10)))
print("Train example batch: \n")
print(train_examples_batch)
print('\n\n\n\nLabels:\n')
print(train_labels_batch)

Train example batch: 

tf.Tensor(
[[b'"Pandemonium" is a horror movie spoof that comes off more stupid than funny. Believe me when I tell you, I love comedies. Especially comedy spoofs. "Airplane", "The Naked Gun" trilogy, "Blazing Saddles", "High Anxiety", and "Spaceballs" are some of my favorite comedies that spoof a particular genre. "Pandemonium" is not up there with those films. Most of the scenes in this movie had me sitting there in stunned silence because the movie wasn\'t all that funny. There are a few laughs in the film, but when you watch a comedy, you expect to laugh a lot more than a few times and that\'s all this film has going for it. Geez, "Scream" had more laughs than this film and that was more of a horror film. How bizarre is that?<br /><br />*1/2 (out of four)'
  b"David Mamet is a very interesting and a very un-equal director. His first movie 'House of Games' was the one I liked best, and it set a series of films with characters whose perspective of life changes a

  b'Not only was this movie better than all the final season of H:LOTS. But it was better than any movie made for TV I have ever seen!<br /><br />Looking at the "Top 250" I see that only one small screen movie has made it: How the Grinch Stole Christmas. I think it is time to increase that group to 2.<br /><br />I will admit that the original series had several shows that were better than this, but I didn\'t mind. I just LOVED being able to enter the world of the Baltimore Homicide Squad again!']], shape=(10, 32), dtype=string)




Labels:

tf.Tensor(
[[0 0 1 0 0 0 1 0 1 0 1 0 0 1 0 1 1 1 0 1 0 0 1 1 0 0 0 1 0 0 1 1]
 [1 1 1 1 1 1 1 1 0 0 1 1 0 1 0 0 1 1 0 1 0 1 1 1 0 0 1 1 1 1 1 0]
 [0 1 0 1 0 1 0 0 0 1 0 0 1 1 0 0 0 1 0 1 0 0 1 0 0 1 1 0 0 1 0 1]
 [1 0 1 1 1 1 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 1 0 0 1 1 0 1 0 1 1]
 [0 1 0 1 1 1 0 0 0 1 1 0 0 1 1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 0 0 1]
 [0 0 1 0 1 0 1 1 0 1 0 0 1 0 0 0 1 0 1 1 0 0 0 1 1 1 1 1 1 0 0 0]
 [0 1 1 1 1 0 1 0 1 0 0 0 1 1 0 0 0 1 1 

In [87]:
train_examples_batch = train_examples_batch.numpy()[0]
train_labels_batch = train_labels_batch.numpy()[0]

validation_data_batch = next(iter(validation_data.batch(32))) 
train_data_batch = next(iter(train_data.batch(32)))


In [88]:
next(iter(validation_data.batch(32))) 

(<tf.Tensor: shape=(32, 32), dtype=string, numpy=
 array([[b"(spoilers)<br /><br />I shoulda figured. The dvd didn't even show the time or how long it was. I thought Wild Cardz was the worst anime movie I'd ever seen. This one is much worse. Makes no sense. Thrown together plot. All so we can see oversized breasts on a figure that doesn't support them. <br /><br />It had to of been a student film. That musta gotten a C grade<br /><br />2/10<br /><br />Quality: 1/10 Entertainment: 6/10 (until I found out it wasn't going to end.) the ending made no darn sense<br /><br />Replayable: 0/10",
         b"What this movie fails from answering is how wrong this war is (and most US wars recently made only to get some oil).<br /><br />How many innocent civilian casualties there has been, how many lives perished and how blatantly stupid the perpetrators are.<br /><br />So, let me ask you - if American soldier kills women and children apart from enemy, its OK, but if government accidentally kills th

In [89]:
# Building the model
# First embedding layer
embedding = "https://tfhub.dev/google/nnlm-en-dim50/2"
hub_layer = hub.KerasLayer(embedding, input_shape=[],
                          dtype=tf.string, trainable=True)
hub_layer(train_examples_batch[:3])

<tf.Tensor: shape=(3, 50), dtype=float32, numpy=
array([[ 0.964519  ,  0.12235046, -0.35730854,  0.48033378,  0.18034822,
        -0.18373251, -0.03941955, -0.22600542, -0.32746387,  0.3865721 ,
         0.2286384 ,  0.00236568, -0.07970965,  0.06908172, -0.273917  ,
        -0.25015512, -0.17116444,  0.10235601,  0.13415377, -0.6560994 ,
        -0.01646905, -0.18063518,  0.7175045 ,  0.15740581, -0.57366866,
         0.02249735, -1.2577188 ,  0.21991247,  0.5483787 , -0.2534604 ,
        -0.5942718 , -0.05421532,  0.2442439 , -0.02258026, -0.22258581,
         0.60274124, -0.02160914,  0.07075842,  0.09879221, -0.44222328,
        -0.02986133,  0.19645615, -0.61093885, -0.18569276, -0.23887902,
        -0.3891516 , -0.35830313, -0.25282302,  0.3660045 ,  0.06032449],
       [ 0.76805687,  0.37268633,  0.5389303 ,  0.38905075, -0.08719452,
        -0.40928397, -0.09052341, -0.35153955, -0.58467203, -0.08505731,
        -0.25557598,  0.06093939, -0.147848  ,  0.17880681,  0.25342456,
 

In [90]:
# Full model
model = tf.keras.Sequential()
model.add(hub_layer)
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(1))
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
keras_layer_8 (KerasLayer)   (None, 50)                48190600  
_________________________________________________________________
dense_4 (Dense)              (None, 16)                816       
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 17        
Total params: 48,191,433
Trainable params: 48,191,433
Non-trainable params: 0
_________________________________________________________________


In [91]:
# compiling model
model.compile(optimizer='adam',
             loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
             metrics=['accuracy'])

In [95]:
# Training the model
history = model.fit(train_data,
                   epochs=5,
                   validation_data=validation_data,
                   verbose=1)

Epoch 1/5


185/625 [=======>......................] - ETA: 10:52 - loss: 0.3887 - accuracy: 0.843 - ETA: 8:35 - loss: 0.3904 - accuracy: 0.859 - ETA: 8:35 - loss: 0.3682 - accuracy: 0.87 - ETA: 8:44 - loss: 0.3625 - accuracy: 0.89 - ETA: 8:41 - loss: 0.3594 - accuracy: 0.90 - ETA: 8:37 - loss: 0.3570 - accuracy: 0.89 - ETA: 8:35 - loss: 0.3473 - accuracy: 0.90 - ETA: 8:40 - loss: 0.3428 - accuracy: 0.90 - ETA: 8:46 - loss: 0.3413 - accuracy: 0.89 - ETA: 8:43 - loss: 0.3442 - accuracy: 0.89 - ETA: 8:39 - loss: 0.3446 - accuracy: 0.89 - ETA: 8:37 - loss: 0.3442 - accuracy: 0.89 - ETA: 8:34 - loss: 0.3387 - accuracy: 0.89 - ETA: 8:32 - loss: 0.3389 - accuracy: 0.90 - ETA: 8:32 - loss: 0.3338 - accuracy: 0.90 - ETA: 8:32 - loss: 0.3340 - accuracy: 0.90 - ETA: 8:32 - loss: 0.3408 - accuracy: 0.90 - ETA: 8:31 - loss: 0.3408 - accuracy: 0.89 - ETA: 8:30 - loss: 0.3398 - accuracy: 0.88 - ETA: 8:29 - loss: 0.3409 - accuracy: 0.88 - ETA: 8:27 - loss: 0.3381 - accuracy: 0.88 - ETA: 8:25 - loss: 0.3353 - acc

371/625 [================>.............] - ETA: 6:08 - loss: 0.3521 - accuracy: 0.84 - ETA: 6:07 - loss: 0.3520 - accuracy: 0.84 - ETA: 6:07 - loss: 0.3519 - accuracy: 0.84 - ETA: 6:06 - loss: 0.3520 - accuracy: 0.85 - ETA: 6:05 - loss: 0.3521 - accuracy: 0.85 - ETA: 6:04 - loss: 0.3524 - accuracy: 0.85 - ETA: 6:03 - loss: 0.3521 - accuracy: 0.85 - ETA: 6:02 - loss: 0.3528 - accuracy: 0.84 - ETA: 6:02 - loss: 0.3530 - accuracy: 0.84 - ETA: 6:01 - loss: 0.3531 - accuracy: 0.84 - ETA: 6:00 - loss: 0.3537 - accuracy: 0.84 - ETA: 5:59 - loss: 0.3536 - accuracy: 0.84 - ETA: 5:58 - loss: 0.3536 - accuracy: 0.84 - ETA: 5:57 - loss: 0.3530 - accuracy: 0.85 - ETA: 5:57 - loss: 0.3524 - accuracy: 0.85 - ETA: 5:56 - loss: 0.3528 - accuracy: 0.84 - ETA: 5:56 - loss: 0.3518 - accuracy: 0.85 - ETA: 5:55 - loss: 0.3517 - accuracy: 0.85 - ETA: 5:55 - loss: 0.3520 - accuracy: 0.85 - ETA: 5:54 - loss: 0.3522 - accuracy: 0.84 - ETA: 5:53 - loss: 0.3519 - accuracy: 0.84 - ETA: 5:53 - loss: 0.3529 - accura

557/625 [=========================>....] - ETA: 3:44 - loss: 0.3420 - accuracy: 0.85 - ETA: 3:44 - loss: 0.3419 - accuracy: 0.85 - ETA: 3:43 - loss: 0.3415 - accuracy: 0.85 - ETA: 3:42 - loss: 0.3420 - accuracy: 0.85 - ETA: 3:42 - loss: 0.3419 - accuracy: 0.85 - ETA: 3:41 - loss: 0.3418 - accuracy: 0.85 - ETA: 3:40 - loss: 0.3416 - accuracy: 0.85 - ETA: 3:40 - loss: 0.3417 - accuracy: 0.85 - ETA: 3:39 - loss: 0.3415 - accuracy: 0.85 - ETA: 3:38 - loss: 0.3417 - accuracy: 0.85 - ETA: 3:38 - loss: 0.3414 - accuracy: 0.85 - ETA: 3:37 - loss: 0.3411 - accuracy: 0.85 - ETA: 3:36 - loss: 0.3407 - accuracy: 0.85 - ETA: 3:36 - loss: 0.3409 - accuracy: 0.85 - ETA: 3:35 - loss: 0.3407 - accuracy: 0.85 - ETA: 3:34 - loss: 0.3407 - accuracy: 0.85 - ETA: 3:34 - loss: 0.3407 - accuracy: 0.85 - ETA: 3:33 - loss: 0.3404 - accuracy: 0.85 - ETA: 3:32 - loss: 0.3399 - accuracy: 0.85 - ETA: 3:32 - loss: 0.3394 - accuracy: 0.85 - ETA: 3:31 - loss: 0.3391 - accuracy: 0.85 - ETA: 3:30 - loss: 0.3389 - accura

625/625 [==============================] - ETA: 1:05 - loss: 0.3262 - accuracy: 0.85 - ETA: 1:04 - loss: 0.3260 - accuracy: 0.85 - ETA: 1:03 - loss: 0.3258 - accuracy: 0.85 - ETA: 1:02 - loss: 0.3258 - accuracy: 0.85 - ETA: 1:01 - loss: 0.3259 - accuracy: 0.85 - ETA: 1:00 - loss: 0.3258 - accuracy: 0.85 - ETA: 59s - loss: 0.3261 - accuracy: 0.8583 - ETA: 58s - loss: 0.3262 - accuracy: 0.858 - ETA: 57s - loss: 0.3261 - accuracy: 0.858 - ETA: 56s - loss: 0.3260 - accuracy: 0.858 - ETA: 55s - loss: 0.3261 - accuracy: 0.858 - ETA: 54s - loss: 0.3261 - accuracy: 0.858 - ETA: 53s - loss: 0.3263 - accuracy: 0.858 - ETA: 53s - loss: 0.3260 - accuracy: 0.858 - ETA: 52s - loss: 0.3259 - accuracy: 0.858 - ETA: 51s - loss: 0.3257 - accuracy: 0.858 - ETA: 50s - loss: 0.3259 - accuracy: 0.858 - ETA: 49s - loss: 0.3258 - accuracy: 0.858 - ETA: 48s - loss: 0.3259 - accuracy: 0.858 - ETA: 47s - loss: 0.3261 - accuracy: 0.858 - ETA: 46s - loss: 0.3263 - accuracy: 0.858 - ETA: 45s - loss: 0.3262 - accura

183/625 [=======>......................] - ETA: 11:55 - loss: 0.1226 - accuracy: 0.968 - ETA: 11:53 - loss: 0.1438 - accuracy: 0.968 - ETA: 11:37 - loss: 0.1161 - accuracy: 0.968 - ETA: 11:36 - loss: 0.1075 - accuracy: 0.968 - ETA: 11:23 - loss: 0.1104 - accuracy: 0.968 - ETA: 11:18 - loss: 0.1038 - accuracy: 0.963 - ETA: 11:13 - loss: 0.0973 - accuracy: 0.964 - ETA: 11:23 - loss: 0.0970 - accuracy: 0.964 - ETA: 11:44 - loss: 0.0956 - accuracy: 0.965 - ETA: 11:35 - loss: 0.1197 - accuracy: 0.953 - ETA: 11:27 - loss: 0.1305 - accuracy: 0.951 - ETA: 11:18 - loss: 0.1305 - accuracy: 0.953 - ETA: 11:11 - loss: 0.1263 - accuracy: 0.954 - ETA: 11:13 - loss: 0.1227 - accuracy: 0.957 - ETA: 11:12 - loss: 0.1187 - accuracy: 0.960 - ETA: 11:21 - loss: 0.1179 - accuracy: 0.960 - ETA: 11:22 - loss: 0.1199 - accuracy: 0.961 - ETA: 11:22 - loss: 0.1194 - accuracy: 0.961 - ETA: 11:26 - loss: 0.1215 - accuracy: 0.960 - ETA: 11:24 - loss: 0.1218 - accuracy: 0.960 - ETA: 11:20 - loss: 0.1200 - accuracy:

369/625 [================>.............] - ETA: 8:16 - loss: 0.1393 - accuracy: 0.94 - ETA: 8:15 - loss: 0.1391 - accuracy: 0.94 - ETA: 8:14 - loss: 0.1387 - accuracy: 0.95 - ETA: 8:12 - loss: 0.1386 - accuracy: 0.95 - ETA: 8:11 - loss: 0.1386 - accuracy: 0.95 - ETA: 8:09 - loss: 0.1387 - accuracy: 0.94 - ETA: 8:08 - loss: 0.1390 - accuracy: 0.94 - ETA: 8:08 - loss: 0.1396 - accuracy: 0.94 - ETA: 8:07 - loss: 0.1393 - accuracy: 0.95 - ETA: 8:06 - loss: 0.1399 - accuracy: 0.94 - ETA: 8:05 - loss: 0.1402 - accuracy: 0.94 - ETA: 8:04 - loss: 0.1400 - accuracy: 0.94 - ETA: 8:03 - loss: 0.1405 - accuracy: 0.94 - ETA: 8:02 - loss: 0.1406 - accuracy: 0.94 - ETA: 8:00 - loss: 0.1409 - accuracy: 0.94 - ETA: 7:59 - loss: 0.1405 - accuracy: 0.94 - ETA: 7:58 - loss: 0.1403 - accuracy: 0.94 - ETA: 7:56 - loss: 0.1409 - accuracy: 0.94 - ETA: 7:55 - loss: 0.1404 - accuracy: 0.94 - ETA: 7:54 - loss: 0.1402 - accuracy: 0.94 - ETA: 7:52 - loss: 0.1401 - accuracy: 0.94 - ETA: 7:51 - loss: 0.1404 - accura

555/625 [=========================>....] - ETA: 4:47 - loss: 0.1422 - accuracy: 0.94 - ETA: 4:46 - loss: 0.1419 - accuracy: 0.94 - ETA: 4:45 - loss: 0.1418 - accuracy: 0.94 - ETA: 4:44 - loss: 0.1420 - accuracy: 0.94 - ETA: 4:42 - loss: 0.1418 - accuracy: 0.94 - ETA: 4:41 - loss: 0.1424 - accuracy: 0.94 - ETA: 4:40 - loss: 0.1423 - accuracy: 0.94 - ETA: 4:39 - loss: 0.1424 - accuracy: 0.94 - ETA: 4:38 - loss: 0.1423 - accuracy: 0.94 - ETA: 4:36 - loss: 0.1424 - accuracy: 0.94 - ETA: 4:35 - loss: 0.1423 - accuracy: 0.94 - ETA: 4:34 - loss: 0.1424 - accuracy: 0.94 - ETA: 4:33 - loss: 0.1422 - accuracy: 0.94 - ETA: 4:32 - loss: 0.1420 - accuracy: 0.94 - ETA: 4:30 - loss: 0.1418 - accuracy: 0.94 - ETA: 4:29 - loss: 0.1417 - accuracy: 0.94 - ETA: 4:28 - loss: 0.1416 - accuracy: 0.94 - ETA: 4:27 - loss: 0.1418 - accuracy: 0.94 - ETA: 4:25 - loss: 0.1417 - accuracy: 0.94 - ETA: 4:24 - loss: 0.1416 - accuracy: 0.94 - ETA: 4:23 - loss: 0.1413 - accuracy: 0.94 - ETA: 4:22 - loss: 0.1411 - accura

625/625 [==============================] - ETA: 1:19 - loss: 0.1372 - accuracy: 0.95 - ETA: 1:18 - loss: 0.1374 - accuracy: 0.95 - ETA: 1:17 - loss: 0.1373 - accuracy: 0.95 - ETA: 1:16 - loss: 0.1372 - accuracy: 0.95 - ETA: 1:15 - loss: 0.1372 - accuracy: 0.95 - ETA: 1:14 - loss: 0.1374 - accuracy: 0.95 - ETA: 1:12 - loss: 0.1374 - accuracy: 0.95 - ETA: 1:11 - loss: 0.1374 - accuracy: 0.95 - ETA: 1:10 - loss: 0.1376 - accuracy: 0.95 - ETA: 1:09 - loss: 0.1375 - accuracy: 0.95 - ETA: 1:08 - loss: 0.1374 - accuracy: 0.95 - ETA: 1:06 - loss: 0.1375 - accuracy: 0.95 - ETA: 1:05 - loss: 0.1374 - accuracy: 0.95 - ETA: 1:04 - loss: 0.1375 - accuracy: 0.95 - ETA: 1:03 - loss: 0.1376 - accuracy: 0.95 - ETA: 1:02 - loss: 0.1375 - accuracy: 0.95 - ETA: 1:01 - loss: 0.1376 - accuracy: 0.95 - ETA: 59s - loss: 0.1375 - accuracy: 0.9514 - ETA: 58s - loss: 0.1377 - accuracy: 0.951 - ETA: 57s - loss: 0.1377 - accuracy: 0.951 - ETA: 56s - loss: 0.1379 - accuracy: 0.951 - ETA: 55s - loss: 0.1385 - accura

183/625 [=======>......................] - ETA: 11:25 - loss: 0.0685 - accuracy: 0.968 - ETA: 10:49 - loss: 0.0739 - accuracy: 0.968 - ETA: 11:04 - loss: 0.0579 - accuracy: 0.979 - ETA: 12:06 - loss: 0.0518 - accuracy: 0.984 - ETA: 13:00 - loss: 0.0639 - accuracy: 0.981 - ETA: 12:50 - loss: 0.0561 - accuracy: 0.984 - ETA: 12:36 - loss: 0.0508 - accuracy: 0.986 - ETA: 12:24 - loss: 0.0543 - accuracy: 0.984 - ETA: 12:10 - loss: 0.0508 - accuracy: 0.986 - ETA: 12:40 - loss: 0.0747 - accuracy: 0.981 - ETA: 12:53 - loss: 0.0832 - accuracy: 0.980 - ETA: 12:59 - loss: 0.0794 - accuracy: 0.981 - ETA: 13:05 - loss: 0.0753 - accuracy: 0.983 - ETA: 13:10 - loss: 0.0714 - accuracy: 0.984 - ETA: 13:01 - loss: 0.0690 - accuracy: 0.985 - ETA: 12:55 - loss: 0.0679 - accuracy: 0.984 - ETA: 12:51 - loss: 0.0681 - accuracy: 0.985 - ETA: 12:50 - loss: 0.0676 - accuracy: 0.984 - ETA: 12:52 - loss: 0.0705 - accuracy: 0.983 - ETA: 13:06 - loss: 0.0692 - accuracy: 0.984 - ETA: 13:20 - loss: 0.0689 - accuracy:

369/625 [================>.............] - ETA: 6:52 - loss: 0.0666 - accuracy: 0.98 - ETA: 6:51 - loss: 0.0663 - accuracy: 0.98 - ETA: 6:50 - loss: 0.0661 - accuracy: 0.98 - ETA: 6:48 - loss: 0.0660 - accuracy: 0.98 - ETA: 6:47 - loss: 0.0661 - accuracy: 0.98 - ETA: 6:46 - loss: 0.0661 - accuracy: 0.98 - ETA: 6:44 - loss: 0.0660 - accuracy: 0.98 - ETA: 6:43 - loss: 0.0664 - accuracy: 0.98 - ETA: 6:42 - loss: 0.0663 - accuracy: 0.98 - ETA: 6:41 - loss: 0.0668 - accuracy: 0.98 - ETA: 6:40 - loss: 0.0670 - accuracy: 0.98 - ETA: 6:38 - loss: 0.0670 - accuracy: 0.98 - ETA: 6:37 - loss: 0.0673 - accuracy: 0.98 - ETA: 6:36 - loss: 0.0676 - accuracy: 0.98 - ETA: 6:35 - loss: 0.0679 - accuracy: 0.98 - ETA: 6:33 - loss: 0.0677 - accuracy: 0.98 - ETA: 6:32 - loss: 0.0676 - accuracy: 0.98 - ETA: 6:31 - loss: 0.0680 - accuracy: 0.98 - ETA: 6:30 - loss: 0.0677 - accuracy: 0.98 - ETA: 6:29 - loss: 0.0676 - accuracy: 0.98 - ETA: 6:27 - loss: 0.0675 - accuracy: 0.98 - ETA: 6:26 - loss: 0.0676 - accura

555/625 [=========================>....] - ETA: 3:43 - loss: 0.0653 - accuracy: 0.98 - ETA: 3:42 - loss: 0.0651 - accuracy: 0.98 - ETA: 3:41 - loss: 0.0651 - accuracy: 0.98 - ETA: 3:40 - loss: 0.0652 - accuracy: 0.98 - ETA: 3:39 - loss: 0.0651 - accuracy: 0.98 - ETA: 3:38 - loss: 0.0652 - accuracy: 0.98 - ETA: 3:37 - loss: 0.0651 - accuracy: 0.98 - ETA: 3:36 - loss: 0.0651 - accuracy: 0.98 - ETA: 3:35 - loss: 0.0649 - accuracy: 0.98 - ETA: 3:34 - loss: 0.0650 - accuracy: 0.98 - ETA: 3:33 - loss: 0.0649 - accuracy: 0.98 - ETA: 3:32 - loss: 0.0649 - accuracy: 0.98 - ETA: 3:32 - loss: 0.0649 - accuracy: 0.98 - ETA: 3:31 - loss: 0.0648 - accuracy: 0.98 - ETA: 3:30 - loss: 0.0646 - accuracy: 0.98 - ETA: 3:29 - loss: 0.0646 - accuracy: 0.98 - ETA: 3:28 - loss: 0.0645 - accuracy: 0.98 - ETA: 3:27 - loss: 0.0645 - accuracy: 0.98 - ETA: 3:26 - loss: 0.0644 - accuracy: 0.98 - ETA: 3:26 - loss: 0.0643 - accuracy: 0.98 - ETA: 3:25 - loss: 0.0642 - accuracy: 0.98 - ETA: 3:24 - loss: 0.0640 - accura

625/625 [==============================] - ETA: 59s - loss: 0.0581 - accuracy: 0.9836 - ETA: 58s - loss: 0.0582 - accuracy: 0.983 - ETA: 57s - loss: 0.0581 - accuracy: 0.983 - ETA: 56s - loss: 0.0580 - accuracy: 0.983 - ETA: 55s - loss: 0.0581 - accuracy: 0.983 - ETA: 54s - loss: 0.0581 - accuracy: 0.983 - ETA: 54s - loss: 0.0581 - accuracy: 0.983 - ETA: 53s - loss: 0.0580 - accuracy: 0.983 - ETA: 52s - loss: 0.0580 - accuracy: 0.983 - ETA: 51s - loss: 0.0579 - accuracy: 0.983 - ETA: 50s - loss: 0.0579 - accuracy: 0.983 - ETA: 49s - loss: 0.0579 - accuracy: 0.983 - ETA: 48s - loss: 0.0578 - accuracy: 0.983 - ETA: 48s - loss: 0.0578 - accuracy: 0.983 - ETA: 47s - loss: 0.0578 - accuracy: 0.983 - ETA: 46s - loss: 0.0577 - accuracy: 0.983 - ETA: 45s - loss: 0.0577 - accuracy: 0.983 - ETA: 44s - loss: 0.0576 - accuracy: 0.983 - ETA: 43s - loss: 0.0576 - accuracy: 0.983 - ETA: 43s - loss: 0.0576 - accuracy: 0.983 - ETA: 42s - loss: 0.0577 - accuracy: 0.983 - ETA: 41s - loss: 0.0582 - accura

186/625 [=======>......................] - ETA: 8:37 - loss: 0.0339 - accuracy: 1.00 - ETA: 7:59 - loss: 0.0272 - accuracy: 1.00 - ETA: 7:58 - loss: 0.0216 - accuracy: 1.00 - ETA: 7:57 - loss: 0.0223 - accuracy: 1.00 - ETA: 7:56 - loss: 0.0436 - accuracy: 0.99 - ETA: 7:54 - loss: 0.0377 - accuracy: 0.99 - ETA: 7:54 - loss: 0.0327 - accuracy: 0.99 - ETA: 7:53 - loss: 0.0317 - accuracy: 0.99 - ETA: 7:52 - loss: 0.0291 - accuracy: 0.99 - ETA: 7:51 - loss: 0.0478 - accuracy: 0.99 - ETA: 7:50 - loss: 0.0453 - accuracy: 0.99 - ETA: 7:49 - loss: 0.0421 - accuracy: 0.99 - ETA: 7:48 - loss: 0.0392 - accuracy: 0.99 - ETA: 7:47 - loss: 0.0366 - accuracy: 0.99 - ETA: 7:51 - loss: 0.0350 - accuracy: 0.99 - ETA: 7:52 - loss: 0.0331 - accuracy: 0.99 - ETA: 7:52 - loss: 0.0327 - accuracy: 0.99 - ETA: 7:51 - loss: 0.0324 - accuracy: 0.99 - ETA: 7:50 - loss: 0.0323 - accuracy: 0.99 - ETA: 7:49 - loss: 0.0312 - accuracy: 0.99 - ETA: 7:49 - loss: 0.0308 - accuracy: 0.99 - ETA: 7:48 - loss: 0.0303 - accura

372/625 [================>.............] - ETA: 5:47 - loss: 0.0239 - accuracy: 0.99 - ETA: 5:46 - loss: 0.0240 - accuracy: 0.99 - ETA: 5:45 - loss: 0.0239 - accuracy: 0.99 - ETA: 5:44 - loss: 0.0239 - accuracy: 0.99 - ETA: 5:44 - loss: 0.0238 - accuracy: 0.99 - ETA: 5:43 - loss: 0.0237 - accuracy: 0.99 - ETA: 5:42 - loss: 0.0242 - accuracy: 0.99 - ETA: 5:42 - loss: 0.0242 - accuracy: 0.99 - ETA: 5:41 - loss: 0.0242 - accuracy: 0.99 - ETA: 5:40 - loss: 0.0242 - accuracy: 0.99 - ETA: 5:39 - loss: 0.0246 - accuracy: 0.99 - ETA: 5:39 - loss: 0.0247 - accuracy: 0.99 - ETA: 5:38 - loss: 0.0246 - accuracy: 0.99 - ETA: 5:37 - loss: 0.0246 - accuracy: 0.99 - ETA: 5:37 - loss: 0.0247 - accuracy: 0.99 - ETA: 5:36 - loss: 0.0246 - accuracy: 0.99 - ETA: 5:35 - loss: 0.0246 - accuracy: 0.99 - ETA: 5:34 - loss: 0.0245 - accuracy: 0.99 - ETA: 5:34 - loss: 0.0245 - accuracy: 0.99 - ETA: 5:33 - loss: 0.0245 - accuracy: 0.99 - ETA: 5:32 - loss: 0.0244 - accuracy: 0.99 - ETA: 5:32 - loss: 0.0244 - accura

558/625 [=========================>....] - ETA: 3:24 - loss: 0.0248 - accuracy: 0.99 - ETA: 3:23 - loss: 0.0248 - accuracy: 0.99 - ETA: 3:23 - loss: 0.0249 - accuracy: 0.99 - ETA: 3:22 - loss: 0.0250 - accuracy: 0.99 - ETA: 3:21 - loss: 0.0250 - accuracy: 0.99 - ETA: 3:20 - loss: 0.0250 - accuracy: 0.99 - ETA: 3:19 - loss: 0.0249 - accuracy: 0.99 - ETA: 3:19 - loss: 0.0249 - accuracy: 0.99 - ETA: 3:18 - loss: 0.0249 - accuracy: 0.99 - ETA: 3:17 - loss: 0.0248 - accuracy: 0.99 - ETA: 3:16 - loss: 0.0248 - accuracy: 0.99 - ETA: 3:15 - loss: 0.0247 - accuracy: 0.99 - ETA: 3:14 - loss: 0.0248 - accuracy: 0.99 - ETA: 3:14 - loss: 0.0248 - accuracy: 0.99 - ETA: 3:13 - loss: 0.0248 - accuracy: 0.99 - ETA: 3:12 - loss: 0.0249 - accuracy: 0.99 - ETA: 3:11 - loss: 0.0250 - accuracy: 0.99 - ETA: 3:10 - loss: 0.0249 - accuracy: 0.99 - ETA: 3:09 - loss: 0.0250 - accuracy: 0.99 - ETA: 3:09 - loss: 0.0250 - accuracy: 0.99 - ETA: 3:08 - loss: 0.0250 - accuracy: 0.99 - ETA: 3:07 - loss: 0.0250 - accura

625/625 [==============================] - ETA: 53s - loss: 0.0227 - accuracy: 0.995 - ETA: 52s - loss: 0.0227 - accuracy: 0.995 - ETA: 51s - loss: 0.0227 - accuracy: 0.995 - ETA: 50s - loss: 0.0227 - accuracy: 0.995 - ETA: 50s - loss: 0.0227 - accuracy: 0.995 - ETA: 49s - loss: 0.0227 - accuracy: 0.995 - ETA: 48s - loss: 0.0228 - accuracy: 0.995 - ETA: 47s - loss: 0.0228 - accuracy: 0.995 - ETA: 46s - loss: 0.0228 - accuracy: 0.995 - ETA: 46s - loss: 0.0227 - accuracy: 0.995 - ETA: 45s - loss: 0.0227 - accuracy: 0.995 - ETA: 44s - loss: 0.0227 - accuracy: 0.995 - ETA: 43s - loss: 0.0227 - accuracy: 0.995 - ETA: 42s - loss: 0.0227 - accuracy: 0.995 - ETA: 42s - loss: 0.0226 - accuracy: 0.995 - ETA: 41s - loss: 0.0226 - accuracy: 0.995 - ETA: 40s - loss: 0.0226 - accuracy: 0.995 - ETA: 39s - loss: 0.0226 - accuracy: 0.995 - ETA: 38s - loss: 0.0230 - accuracy: 0.995 - ETA: 37s - loss: 0.0231 - accuracy: 0.995 - ETA: 37s - loss: 0.0230 - accuracy: 0.995 - ETA: 36s - loss: 0.0230 - accurac

186/625 [=======>......................] - ETA: 8:13 - loss: 0.0039 - accuracy: 1.00 - ETA: 8:24 - loss: 0.0100 - accuracy: 1.00 - ETA: 8:23 - loss: 0.0082 - accuracy: 1.00 - ETA: 8:24 - loss: 0.0075 - accuracy: 1.00 - ETA: 8:25 - loss: 0.0222 - accuracy: 0.99 - ETA: 8:22 - loss: 0.0191 - accuracy: 0.99 - ETA: 8:23 - loss: 0.0166 - accuracy: 0.99 - ETA: 8:22 - loss: 0.0155 - accuracy: 0.99 - ETA: 8:20 - loss: 0.0139 - accuracy: 0.99 - ETA: 8:20 - loss: 0.0264 - accuracy: 0.99 - ETA: 8:19 - loss: 0.0249 - accuracy: 0.99 - ETA: 8:19 - loss: 0.0232 - accuracy: 0.99 - ETA: 8:18 - loss: 0.0218 - accuracy: 0.99 - ETA: 8:20 - loss: 0.0207 - accuracy: 0.99 - ETA: 8:19 - loss: 0.0206 - accuracy: 0.99 - ETA: 8:18 - loss: 0.0230 - accuracy: 0.99 - ETA: 8:16 - loss: 0.0232 - accuracy: 0.99 - ETA: 8:14 - loss: 0.0221 - accuracy: 0.99 - ETA: 8:12 - loss: 0.0210 - accuracy: 0.99 - ETA: 8:12 - loss: 0.0204 - accuracy: 0.99 - ETA: 8:12 - loss: 0.0200 - accuracy: 0.99 - ETA: 8:10 - loss: 0.0194 - accura

372/625 [================>.............] - ETA: 6:01 - loss: 0.0104 - accuracy: 0.99 - ETA: 6:00 - loss: 0.0104 - accuracy: 0.99 - ETA: 5:59 - loss: 0.0104 - accuracy: 0.99 - ETA: 5:58 - loss: 0.0104 - accuracy: 0.99 - ETA: 5:57 - loss: 0.0105 - accuracy: 0.99 - ETA: 5:57 - loss: 0.0104 - accuracy: 0.99 - ETA: 5:56 - loss: 0.0105 - accuracy: 0.99 - ETA: 5:55 - loss: 0.0105 - accuracy: 0.99 - ETA: 5:54 - loss: 0.0104 - accuracy: 0.99 - ETA: 5:53 - loss: 0.0104 - accuracy: 0.99 - ETA: 5:52 - loss: 0.0105 - accuracy: 0.99 - ETA: 5:51 - loss: 0.0105 - accuracy: 0.99 - ETA: 5:50 - loss: 0.0104 - accuracy: 0.99 - ETA: 5:49 - loss: 0.0104 - accuracy: 0.99 - ETA: 5:48 - loss: 0.0104 - accuracy: 0.99 - ETA: 5:47 - loss: 0.0104 - accuracy: 0.99 - ETA: 5:46 - loss: 0.0103 - accuracy: 0.99 - ETA: 5:45 - loss: 0.0103 - accuracy: 0.99 - ETA: 5:44 - loss: 0.0103 - accuracy: 0.99 - ETA: 5:43 - loss: 0.0103 - accuracy: 0.99 - ETA: 5:43 - loss: 0.0103 - accuracy: 0.99 - ETA: 5:42 - loss: 0.0103 - accura

558/625 [=========================>....] - ETA: 3:25 - loss: 0.0144 - accuracy: 0.99 - ETA: 3:25 - loss: 0.0144 - accuracy: 0.99 - ETA: 3:24 - loss: 0.0144 - accuracy: 0.99 - ETA: 3:23 - loss: 0.0145 - accuracy: 0.99 - ETA: 3:22 - loss: 0.0147 - accuracy: 0.99 - ETA: 3:21 - loss: 0.0150 - accuracy: 0.99 - ETA: 3:21 - loss: 0.0156 - accuracy: 0.99 - ETA: 3:20 - loss: 0.0159 - accuracy: 0.99 - ETA: 3:19 - loss: 0.0159 - accuracy: 0.99 - ETA: 3:18 - loss: 0.0159 - accuracy: 0.99 - ETA: 3:17 - loss: 0.0158 - accuracy: 0.99 - ETA: 3:17 - loss: 0.0158 - accuracy: 0.99 - ETA: 3:16 - loss: 0.0158 - accuracy: 0.99 - ETA: 3:15 - loss: 0.0158 - accuracy: 0.99 - ETA: 3:14 - loss: 0.0158 - accuracy: 0.99 - ETA: 3:14 - loss: 0.0159 - accuracy: 0.99 - ETA: 3:13 - loss: 0.0162 - accuracy: 0.99 - ETA: 3:12 - loss: 0.0164 - accuracy: 0.99 - ETA: 3:11 - loss: 0.0165 - accuracy: 0.99 - ETA: 3:10 - loss: 0.0167 - accuracy: 0.99 - ETA: 3:10 - loss: 0.0168 - accuracy: 0.99 - ETA: 3:09 - loss: 0.0172 - accura

625/625 [==============================] - ETA: 53s - loss: 0.0160 - accuracy: 0.996 - ETA: 53s - loss: 0.0160 - accuracy: 0.996 - ETA: 52s - loss: 0.0160 - accuracy: 0.996 - ETA: 51s - loss: 0.0160 - accuracy: 0.996 - ETA: 50s - loss: 0.0159 - accuracy: 0.996 - ETA: 49s - loss: 0.0159 - accuracy: 0.996 - ETA: 48s - loss: 0.0159 - accuracy: 0.996 - ETA: 48s - loss: 0.0159 - accuracy: 0.996 - ETA: 47s - loss: 0.0158 - accuracy: 0.996 - ETA: 46s - loss: 0.0158 - accuracy: 0.996 - ETA: 45s - loss: 0.0158 - accuracy: 0.996 - ETA: 44s - loss: 0.0158 - accuracy: 0.996 - ETA: 43s - loss: 0.0158 - accuracy: 0.996 - ETA: 43s - loss: 0.0157 - accuracy: 0.996 - ETA: 42s - loss: 0.0158 - accuracy: 0.996 - ETA: 41s - loss: 0.0158 - accuracy: 0.996 - ETA: 40s - loss: 0.0158 - accuracy: 0.996 - ETA: 39s - loss: 0.0157 - accuracy: 0.996 - ETA: 39s - loss: 0.0159 - accuracy: 0.995 - ETA: 38s - loss: 0.0159 - accuracy: 0.995 - ETA: 37s - loss: 0.0158 - accuracy: 0.996 - ETA: 36s - loss: 0.0158 - accurac

In [98]:
# Evaluating the model
loss, accuracy = model.evaluate(test_data)

print("Loss: ", loss)
print("Accuracy: ", accuracy)

543/782 [===================>..........] - ETA: 2:51 - loss: 0.7991 - accuracy: 0.87 - ETA: 14s - loss: 0.3752 - accuracy: 0.9062 - ETA: 13s - loss: 0.4861 - accuracy: 0.875 - ETA: 13s - loss: 0.6179 - accuracy: 0.862 - ETA: 14s - loss: 0.7299 - accuracy: 0.838 - ETA: 13s - loss: 0.7506 - accuracy: 0.828 - ETA: 14s - loss: 0.6944 - accuracy: 0.835 - ETA: 14s - loss: 0.6886 - accuracy: 0.836 - ETA: 14s - loss: 0.6764 - accuracy: 0.838 - ETA: 14s - loss: 0.6813 - accuracy: 0.837 - ETA: 14s - loss: 0.6941 - accuracy: 0.838 - ETA: 14s - loss: 0.6921 - accuracy: 0.838 - ETA: 14s - loss: 0.6804 - accuracy: 0.839 - ETA: 14s - loss: 0.6455 - accuracy: 0.846 - ETA: 14s - loss: 0.6606 - accuracy: 0.843 - ETA: 15s - loss: 0.6776 - accuracy: 0.841 - ETA: 15s - loss: 0.6710 - accuracy: 0.841 - ETA: 15s - loss: 0.6761 - accuracy: 0.841 - ETA: 15s - loss: 0.6865 - accuracy: 0.838 - ETA: 15s - loss: 0.6816 - accuracy: 0.838 - ETA: 15s - loss: 0.6762 - accuracy: 0.840 - ETA: 15s - loss: 0.6675 - accura

782/782 [==============================] - ETA: 5s - loss: 0.6557 - accuracy: 0.84 - ETA: 4s - loss: 0.6544 - accuracy: 0.84 - ETA: 4s - loss: 0.6540 - accuracy: 0.84 - ETA: 4s - loss: 0.6560 - accuracy: 0.84 - ETA: 4s - loss: 0.6556 - accuracy: 0.84 - ETA: 4s - loss: 0.6551 - accuracy: 0.84 - ETA: 4s - loss: 0.6548 - accuracy: 0.84 - ETA: 4s - loss: 0.6542 - accuracy: 0.84 - ETA: 4s - loss: 0.6527 - accuracy: 0.84 - ETA: 4s - loss: 0.6515 - accuracy: 0.84 - ETA: 4s - loss: 0.6515 - accuracy: 0.84 - ETA: 4s - loss: 0.6529 - accuracy: 0.84 - ETA: 4s - loss: 0.6536 - accuracy: 0.84 - ETA: 4s - loss: 0.6531 - accuracy: 0.84 - ETA: 4s - loss: 0.6517 - accuracy: 0.84 - ETA: 4s - loss: 0.6530 - accuracy: 0.84 - ETA: 4s - loss: 0.6527 - accuracy: 0.84 - ETA: 3s - loss: 0.6539 - accuracy: 0.84 - ETA: 3s - loss: 0.6544 - accuracy: 0.84 - ETA: 3s - loss: 0.6548 - accuracy: 0.84 - ETA: 3s - loss: 0.6567 - accuracy: 0.84 - ETA: 3s - loss: 0.6567 - accuracy: 0.84 - ETA: 3s - loss: 0.6561 - accuracy